// Builds `src/power_atlas/static/prism.js`, the vendored syntax highlighter
// behind the code blocks in /acp's transcript. Run it to change the language
// set or to move to a new Prism release — it is the whole provenance of that
// file, which is generated and should never be hand-edited.
//
//   npm pack prismjs@1.30.0 && tar -xzf prismjs-1.30.0.tgz   # yields ./package
//   node _build_prism.mjs ./package
//
// Named like `_check_test_names.py` and `_pre_commit_hook.sh`: repo tooling
// that is not part of the package.
import { readFileSync, writeFileSync, statSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const DEST = join(HERE, "src", "power_atlas", "static", "prism.js");

// Dependency order, which concatenation makes load-bearing: `clike` defines the
// grammar `javascript` extends, `markup` the one `markdown` does, `css` the one
// `scss` does, and `c` the one `cpp` does. Prism's own components.json is where
// each of those is declared; this list is that graph flattened by hand, and a
// language added out of order throws at load rather than silently degrading.
//
// The set is what agent transcripts actually hold, not Prism's whole catalogue
// (~300 grammars, megabytes). A language outside it is not an error: the block
// keeps its label and renders uncoloured, which is exactly what a bare fence
// already does.
const LANGS = [
  "markup", "css", "clike",
  "javascript", "typescript", "jsx",
  "python", "bash", "powershell", "batch",
  "json", "yaml", "toml", "ini",
  "sql", "rust", "go", "ruby", "java", "csharp", "c", "cpp",
  "kotlin", "swift", "lua",
  "markdown", "diff", "docker", "scss",
];

const pkgRoot = resolve(process.argv[2] ?? "");
if (!process.argv[2]) {
  console.error("usage: node _build_prism.mjs <path to extracted prismjs package>");
  process.exit(2);
}
const components = join(pkgRoot, "components");
const version = JSON.parse(readFileSync(join(pkgRoot, "package.json"), "utf8")).version;

const head = `/* Prism ${version} — MIT (c) 2012 Lea Verou — https://prismjs.com
 *
 * GENERATED by _build_prism.mjs. Do not edit: change the language list there
 * and rebuild.
 *
 * Vendored rather than loaded from a CDN, exactly as htmx.min.js is. /acp is
 * served off localhost to watch local agent sessions, so a page whose code
 * blocks stop colouring when the network is down, when a proxy intercepts TLS,
 * or when a third party has an outage is strictly a worse page. It also keeps a
 * third-party origin from serving executable code into the one page that holds
 * the ACP token, the session ids, and a live socket to an agent running with
 * every tool pre-approved.
 *
 * prism-core plus ${LANGS.length} grammars, concatenated in dependency order. No plugins
 * and no theme: the token colours are PowerAtlas's own and live in style.css.
 *
 * \`manual\` is set before core runs and is the whole reason this file is inert
 * on load. Core reads \`_self.Prism.manual\` while building itself, and without
 * it Prism hooks DOMContentLoaded and rewrites every <pre> on the page through
 * innerHTML — the one sink /acp does not have. The page calls Prism.tokenize()
 * and nothing else; nothing here is ever handed a DOM node.
 */
window.Prism = { manual: true };
`;

const parts = [head];
for (const lang of ["core", ...LANGS]) {
  const file = join(components, `prism-${lang}.min.js`);
  parts.push(`\n/* --- prism-${lang} --- */\n`, readFileSync(file, "utf8").trimEnd(), "\n");
}

writeFileSync(DEST, parts.join(""), "utf8");
console.log(`wrote ${DEST}: ${statSync(DEST).size} bytes, ${LANGS.length} grammars`);
